[["输入输出"]]
title = "热身运动"
content = """
从这里开始，我们测试一下 Python 编程的基本格式。
输入**ok**开始测试吧！
"""
blank = ['$']
answer = ['ok']
hint = """
ok
"""

[["输入输出"]]
title = "输出语句"
content = """
输出**黄岩一职**，请补全代码！
"""
blank = ['$$', '"黄岩一职"', '$']
answer = ['print(', ')']
hint = """
print("黄岩一职") 注意使用英文括号！
"""

[["输入输出"]]
title = "输出语句 print()"
content = """
同样这题考察的也是输出语句，请输出**Python 编程入门**，注意文字需要用引号包裹起来，注意空格。
（仔细审题！）
"""
blank = ['print(', '$$$$', ')']
answer = [['"Python 编程入门"', "'Python 编程入门'"]]

[["输入输出"]]
title = "真相只有一个"
content = """
（单选）请选择下列中正确的一项：
"""
type = "选择"
blank = ["""
print=("后来，错过也成了人间常态。")
""", """
Print("你背朝太阳，就只能看到自己的影子。")
""", """
print(既然忘不掉，就把它留在心中，让时间去冲淡它。)
""", """
print("水的清澈，并非因为它不含杂质，而是在于懂得沉淀。")
"""]
answer = ["d"]

[["输入输出"]]
title = "输入语句 input()"
content = """
请输入提示语：**请输入分数**
"""
blank = ["a=input(", "$$$", ")"]
answer = ["\"请输入分数\"", "'请输入分数'"]

[["输入输出"]]
title = "数值计算"
content = """
在 print() 函数中可以直接写算式，Python 会直接计算出式子的运算结果
第一行：计算 114+514 的结果
第二行：计算 10 整除 3 的结果
(注意顺序，不需要你自己计算！)
"""
blank = ['print(', '$$', ')', '\n', 'print(', '$$', ')']
answer = [['114+514', '114 + 514'], ['10//3', '10 // 3']]
hint = """
整除是两个斜杠哦 ~
"""

[["输入输出"]]
title = "求余"
content = """
计算 5 除以 3 的余数，用什么符号表示求余捏？
"""
blank = ['print(', '$$', ')']
answer = ['5%3', '5 % 3']

[["输入输出"]]
title = "用逗号分隔多个输出值"
content = """
在 print() 中可以输出多个内容，之间用**逗号**隔开。
下面有三个空需要填写。
请输出**尼尔 机械纪元**，注意文字用引号包裹。
"""
blank = ['print(', '$$', '$', '$$$', ')']
answer = [['"尼尔"', "'尼尔'"], [',', ', '], ['"机械纪元"', "'机械纪元'"]]
code = ["""
# 举个例子
print("熊大", "熊二", "光头强")
"""]

[["输入输出"]]
title = "输出语句的自定义分隔符号"
content = """
使用 sep="" 可以用于取消多个输出之间的空格。
在引号里面可以写入你想要的分隔符，比如 sep="-"，表示用短横线来连接。
注意逗号和等号！
"""
code = ["""
print("尼尔", "机械纪元", sep="")
# 尼尔机械纪元
print("尼尔", "机械纪元", sep="-")
# 尼尔-机械纪元
"""]

[["输入输出"]]
title = "练习"
content = """
输出的文字用**下划线**连接。
"""
blank = ['print("尼尔", "机械纪元", "自动人形"', '$$$', ')']
answer = [[', sep="_"', ',sep="_"', ",sep='_'", ", sep='_'"]]
hint = """
提示：下划线 _ 就是 SHIFT + 减号
"""

[["输入输出"]]
title = "变量"
content = """
变量是编程中的重要概念，方便我们编写可读性很高的代码。
变量有很多类型，包括文字、数字、真假、列表、字典等。
"""
code = ["""
role_1 = "熊大"
role_2 = "熊二"
role_3 = "光头强"
""", """
money = 1000
height = 1.82
is_success = True
""", """
games = ["塞尔达传说", "重力异想世界", "合金装备", "最终幻想", "风之旅人"]
role = {
    "name": "雷电将军",
    "sex": "女",
}
"""]

[["输入输出"]]
title = "变量的命名规则"
content = """
① 变量名只能用"_"，数字，字母组成
（所以你在变量名中只能看到**下划线**这一个符号，**其他符号都算错！**）
② 不能以数字开头
③ 不能使用**保留字**，像 print input 这类已经有含义的也不能作为变量名
④ 变量名**区分**大小写

* Python 中的保留字：
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
"""
code = ["""
# 复制代码到自测猫运行，可以得到 Python 所有的保留字
import keyword
print(keyword.kwlist)
"""]

[["输入输出"]]
title = "变量的命令规则 1"
content = """
（多选题）以下哪些是【合法】的变量名
"""
type = "选择"
blank = ["and", "app1e", "Ban_Ana", "girl-name", "3cat", "d0G#"]
answer = ["b", "c"]
hint = """
请回到上一页看看保留字
"""

[["输入输出"]]
title = "变量的命令规则 2"
content = """
（多选题）以下哪些是【合法】的变量名，有点难度，要看仔细！
"""
type = "选择"
blank = [
    "_name",
    "name-",
    "na-me",
    "n_ame",
    "-name",
    "~game",
    "g.a.m.e.",
    "ga+me",
    "*game*",
]
answer = ["a", "d"]
hint = """
变量命名有诀窍，请回到上上页看变量命名的第一个规则
"""

[["输入输出"]]
title = "变量的命令规则 3"
content = """
（多选题）以下哪些是【违法】的变量名
"""
type = "选择"
blank = [
    "g@m1",
    "ga/e",
    "#game",
    "game!",
    "break",
    "G_a_m_e",
    "gAME_",
    "game",
    "g_ame",
]
answer = ["a", "b", "c", "d", "e"]

[["输入输出"]]
title = "恭喜你"
content = """
完成测试，可以帮帮其他同学哦！
"""

[["选择结构"]]
title = "选择语句"
content = """
表示**如果**的关键字是：
"""
blank = ['$']
answer = ['if']

[["选择结构"]]
title = "选择语句"
content = """
表示**否则**的关键字是：
"""
blank = ['$$']
answer = ['else']

[["选择结构"]]
title = "选择语句"
content = """
（多选题）阅读下面的代码，找出其中出错的地方
"""
code = ["""
lang=input()
if lang="Python"
    print("Python期中考试")
else lang="C语言"
    print("C语言期中考试")
"""]
type = "选择"
blank = ["等于应该是两个等号", "缺失冒号", "缩进有问题", "else后面不需要接条件"]
answer = ["a", "b", "d"]


[["while循环"]]
title = "热身运动"
content = """
输入 **True** 进入死循环
"""
blank = [
    "while ", "$$", ":", "\n",
    "   print('hello python')"
]
answer = ["True"]
hint = """
True
"""


[["while循环"]]
title = "看看仔细"
content = """
（单选题）下面表示循环的关键字正确的是：
"""
type = "选择"
blank = ["""
while
""", """
While
""", """
whlie
""", """
if
"""]
answer = ["a"]


[["while循环"]]
title = "hello python"
content = """
我希望输出 10 行 hello python ，请你补全代码：
"""
blank = [
    "i=0", "\n",
    "$$"," i<10","$","\n",
    "   i=i+1","\n",
    '   print("hello python")',
]
answer = ["while", ":"]

[["while循环"]]
title = "2 的 N 次方"
content = """
康康学习了 IP 地址，他写了一段代码用来输出 2 的 N 次方：
比如：2 4 8 16 32 64 128 等等
请你阅读以下代码并回答：
"""
code = ["""
n=1
i=0
while i<5:
    i=i+1
    n=n*2
    print(n)
"""]
blank = [
    "一共会输出几行：", "$$", "\n",
    "\n",
    "最终变量 n 的值是多少：", "$$"
]
answer = ["5", "32"]

[["while循环"]]
title = "人生的 365 次方"
content = """
《蜗牛》周杰伦
我要一步一步往上爬
等待阳光静静看着它的脸
小小的天有大大的梦想
我有属于我的天
任风吹干流过的泪和汗
总有一天我有属于我的天
*************************
如果假设你的初始各项能力是 1，如果像蜗牛一样，每天进步一点点。
比如每天提高 1%，那么一个月后，你的能力会是多少呢？
一年后是多少呢？
"""
